#######################################################################
# file name: Makefile
# author   : Yu Liu
# email    : <ilhanwnz@hotmail.com>
# time     : Mon 01 Apr 2019 01:38:08 PM CST
#######################################################################

FILES := 开发人员手册

$(FILES).html: 
	./ToolsOfIm2HTML/Im2Html $(FILES).im $(FILES).html

clean:
	rm -rf *.html
